# use official python image
FROM python:3.10

#  specify envs passing to container
ARG KAFKA_HOST
ARG KAFKA_PORT
ARG KAFKA_CONSUMER_USERNAME
ARG KAFKA_CONSUMER_PASSWORD
ARG KAFKA_CONSUMER_GROUP
ARG KAFKA_SOURCE_TOPIC

ARG PG_WAREHOUSE_HOST
ARG PG_WAREHOUSE_PORT
ARG PG_WAREHOUSE_DBNAME
ARG PG_WAREHOUSE_USER
ARG PG_WAREHOUSE_PASSWORD

# update components in container
RUN apt-get update -y

# copy app files /src/* and requirements.txt to container
COPY /src/. /src/.
COPY /requirements.txt .

# install required Python packages and dependencies
RUN pip install -r requirements.txt

# copy certificates to login to cloud service
RUN mkdir -p /crt
RUN wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" --output-document /crt/YandexInternalRootCA.crt
RUN chmod 0600 /crt/YandexInternalRootCA.crt

WORKDIR /src

# start with python ...
ENTRYPOINT ["python"]

# this script
CMD ["app.py"]